version: '1'
services:
  gui1:
    build:
      context: ./virtual-gui
      args:
        CACHE_BREAKER: ${CACHE_BREAKER}
    container_name: gui1
    networks:
      - gui_net

  gui2:
    build:
      context: ./virtual-gui
      args:
        CACHE_BREAKER: ${CACHE_BREAKER}
    container_name: gui2
    networks:
      - gui_net

  control:
    build:
      context: ./control
      args:
        CACHE_BREAKER: ${CACHE_BREAKER}
    container_name: control
    depends_on:
      - gui1
      - gui2
    networks:
      - gui_net
    volumes:
      - shared_volume:/shared

volumes:
  shared_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SHARED_DIR}

networks:
  gui_net:
    driver: bridge
